version: "3.9"

services:
  app:
    build: .
    command: python -u app/app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db

  db:
    image: mongo:latest
    hostname: localmongo
    environment:
      - MONGO_INITDB_DATABASE=default_db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - ./mongodb:/data/db
    ports:
      - 27017:27017

  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=root
      - ELASTIC_PASSWORD=pass
      - network.host=0.0.0.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./esdata:/usr/share/elasticsearch/data

